[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Josh Schneider", email = "josh.schneider@gmail.com"},
]
dependencies = [
    "mkdocs>=1.4.2",
    "black>=23.1.0",
]
requires-python = ">=3.11"
license = {text = "MIT"}
