name: Build site and release
on:
  workflow_dispatch:
  push:
  pull_request:
    types:
      - closed
jobs:
  build-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3

      - name: Setup Dependencies
        run: pdm sync

      - name: Build site
        run: pdm run mkdocs build

      - name: Archive Exports
        uses: actions/upload-artifact@v3
        with:
          name: Site_Export
          path: site/*
          retention-days: 7

  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3

      - name: Setup Dependencies
        run: pdm sync

      - name: Build site
        run: pdm run mkdocs build

      - name: Tag branch (main only)
        if: endswith(github.ref, 'main')
        uses: mydea/action-tag-date-version@v20
        id: version-tag

      - name: Cut a release (main only)
        uses: ncipollo/release-action@v1
        if: endsWith(github.ref, 'main')
        with:
          artifacts: site/*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version-tag.outputs.version }}
